routes/web.php
        'as'=>'language-chooser',
        'uses'=>'LanguageController@changeLanguage',
    )
    );
    Route::post('/changecurrency', 'Mobile\HomeController@changecurrency');
    Route::post('/order','OrderidController@loadID');
    Route::get('/order', 'OrderidController@loadcoupon');
    Route::get('/orders', 'Mobile\OrderController@orders')->middleware('auth.custom');
    Route::get('/contactinfo', 'Mobile\HomeController@contactinfo')->middleware('auth.custom');
    Route::post('/contactinfo', 'Mobile\HomeController@contactinfo')->middleware('auth.custom');
    Route::get('/passengerinfo', 'Mobile\HomeController@passengerinfo')->middleware('auth.custom');
    Route::post('/passengerinfo', 'Mobile\HomeController@passengerinfo')->middleware('auth.custom');
    Route::get('/mypoints', 'Mobile\HomeController@mypoints')->middleware('auth.custom');
    Route::post('/login', 'Auth\LoginController@login');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::get('/resetpwd', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/resetpwd', 'Auth\ResetPasswordController@reset');
    Route::get('/orders/psginfo/{ID}', 'Mobile\OrderController@orderspsginfo')->middleware('auth.custom');
    Route::get('/policy', 'Mobile\HomeController@policy');
});


$appDevRoutes = function() {
    Route::get('', 'Mobile\HomeController@index');
    Route::get('/paypal', 'Mobile\HomeController@paypal');
    Route::get('/ft-atos', 'Mobile\HomeController@ftatos');
    Route::post('/atos', 'Mobile\HomeController@atos')->name("dev_atos");
    Route::get('/searchlist', 'Mobile\HomeController@searchlist')->name("dev_searchlist");
    Route::get('/review', 'Mobile\HomeController@review')->name("dev_review");
    Route::get('/clean', 'Mobile\HomeController@clean')->name("dev_clean");
    Route::get('/pay', 'Mobile\HomeController@pay')->name("dev_pay");
    Route::get('/search_iframe', 'Mobile\HomeController@search_iframe');
    Route::get('/receipt', 'Mobile\HomeController@receipt');
    Route::get('/paypal_success', 'Mobile\HomeController@paypalsuccess');
    Route::get('/paypal_error', 'Mobile\HomeController@paypalerror');
    Route::post('/language-chooser', 'LanguageController@changeLanguage');
    Route::post('/language',array(
            'before'=>'csrf',
            'as'=>'language-chooser',
            'uses'=>'LanguageController@changeLanguage',
        )
    );
    Route::post('/changecurrency', 'Mobile\HomeController@changecurrency');
    Route::post('/order','OrderidController@loadID');
    Route::get('/order', 'OrderidController@loadcoupon');
    Route::get('/orders', 'Mobile\OrderController@orders')->middleware('auth.custom');
    Route::get('/contactinfo', 'Mobile\HomeController@contactinfo')->middleware('auth.custom');
    Route::post('/contactinfo', 'Mobile\HomeController@contactinfo')->middleware('auth.custom');
    Route::get('/passengerinfo', 'Mobile\HomeController@passengerinfo')->middleware('auth.custom');
    Route::post('/passengerinfo', 'Mobile\HomeController@passengerinfo')->middleware('auth.custom');
    Route::get('/mypoints', 'Mobile\HomeController@mypoints')->middleware('auth.custom');
    Route::post('/login', 'Auth\LoginController@login');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::get('/resetpwd', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/resetpwd', 'Auth\ResetPasswordController@reset');
    Route::get('/orders/psginfo/{ID}', 'Mobile\OrderController@orderspsginfo')->middleware('auth.custom');
    Route::get('/policy', 'Mobile\HomeController@policy');
};

if($_SERVER["HTTP_HOST"] == 'dev.mo.air.sinorama.ca') {
    Route::group(['domain' => 'dev.mo.air.sinorama.ca'], $appDevRoutes);
}

if($_SERVER["HTTP_HOST"] == 'localhost') {
    Route::group(['domain' => 'localhost'], $appDevRoutes);
}

if($_SERVER["HTTP_HOST"] == '192.168.0.149') {
    Route::group(['domain' => '192.168.0.149'], $appDevRoutes);
}

Route::group(['domain' => 'de.air.sinorama.ca'], function (){
    Route::get('', 'Desktop\HomeController@index');

    Route::match(['get', 'post'],'/booking', 'Desktop\HomeController@booking')->name("booking");
});

Route::group(['middleware'=>'csrf'],function() {
    Route::post('/atos_cancel', 'Mobile\HomeController@atoscancel');
    Route::post('/atos_success','Mobile\HomeController@atossuccess');
    Route::post('/atos_return', 'Mobile\HomeController@atosreturn');

});

/*Route::group(['domain' => 'mo.air.sinorama.test'], function (){
    Route::get('', 'Mobile\HomeController@index');
    Route::get('/paypal', 'Mobile\HomeController@paypal');
    Route::get('/ft-atos', 'Mobile\HomeController@ftatos');
    Route::post('/atos', 'Mobile\HomeController@atos')->name("dev_atos");
    Route::get('/searchlist', 'Mobile\HomeController@searchlist')->name("dev_searchlist");
    Route::get('/review', 'Mobile\HomeController@review')->name("dev_review");
    Route::get('/clean', 'Mobile\HomeController@clean')->name("dev_clean");
    Route::get('/pay', 'Mobile\HomeController@pay')->name("dev_pay");
    Route::get('/search_iframe', 'Mobile\HomeController@search_iframe');
    Route::get('/receipt', 'Mobile\HomeController@receipt');
    Route::get('/paypal_success', 'Mobile\HomeController@paypalsuccess');
    Route::get('/paypal_error', 'Mobile\HomeController@paypalerror');
    Route::post('/language-chooser', 'LanguageController@changeLanguage');
    Route::post('/language',array(
            'before'=>'csrf',
            'as'=>'language-chooser',
            'uses'=>'LanguageController@changeLanguage',
        )
    );
    Route::post('/order','OrderidController@loadID');
    Route::get('/order', 'OrderidController@loadcoupon');
    Route::get('/orders', 'Mobile\OrderController@orders');
    Route::get('/contactinfo', 'Mobile\HomeController@contactinfo');
    Route::post('/contactinfo', 'Mobile\HomeController@contactinfo');
    Route::get('/passengerinfo', 'Mobile\HomeController@passengerinfo');
    Route::post('/passengerinfo', 'Mobile\HomeController@passengerinfo');
    Route::get('/mypoints', 'Mobile\HomeController@mypoints');
    Route::post('/login', 'Auth\LoginController@login');
    Route::get('/logout', 'Auth\LoginController@logout');
});*/

/*
Route::group(['middleware' => ['isVerified']], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/home', 'HomeController@index')->name('home');
    //accounts

    Route::get('/account/cashpage', 'AccountController@cashpage')->name('cashpage');
    Route::get('/account/pointpage', 'AccountController@pointpage')->name('pointpage');
    Route::get('/account/profile', 'AccountController@profile')->name('profile');
    Route::get('/account/becomeingagent', 'AccountController@profile')->name('becomeingagent');
    //orders
    Route::get('/order/flightorder', 'OrderController@recentorders')->name('flightrecentorder');
    Route::get('/order/flighthistoryorder', 'OrderController@historyorders')->name('flighthistoryorder');
    Route::get('/order/orderdetail', 'OrderController@orderdetail')->name('orderdetail');
    Route::get('/order/payit', 'OrderController@orderdetail')->name('payit');
    Route::post('/order/chargepointsaccount', 'OrderController@chargeAccountPoints')->name('changeaccountpoints');

    Route::post('/order/paywithpoints', 'OrderController@querypaypointsinfo')->name('querypaypointsinfo');
    Route::post('/order/paywithaccount', 'OrderController@querypayaccountinfo')->name('querypayaccountinfo');

    Route::get('/order/invoice', 'OrderController@orderdetail')->name('invoice');

    Route::get('/contract/search', 'ContractController@searchContract')->name('searchcontract');
    Route::get('/contract/commission', 'ContractController@getCommissionOfContract')->name('commission');

    //GDS

    Route::post('/gds/pnrpassengerCard', 'GdsController@pnrPassngerCard')->name('passengercard');
    Route::post('/gds/calculatecommission', 'GdsController@calculatePNRCommission')->name('gdscalculatecommission');

    //AGENT

    Route::get('/agent/calculatecommission', 'AgentController@calculateCommission')->name('calculatecommission');
    Route::get('/agent/issueairticekt', 'AgentController@issueAirTicekt')->name('issueairticekt');

    Route::get('/agent/applicationlist','AgentController@application')->name('applicationlist');

});


Route::get('/logout', 'HomeController@logout')->name('logout');

Route::group( ['middleware' => ['auth']], function() {
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('agents', 'AgentController');
});

Route::group([
    'middleware' => 'web'
], function () {
    Route::get('email-verification/error', 'Auth\RegisterController@getVerificationError')
        ->name('email-verification.error');
    Route::get('email-verification/check/{token}', 'Auth\RegisterController@getVerification')
        ->name('email-verification.check');
    Route::post('email-verification/resend', 'Auth\RegisterController@resendEmail')
        ->name('email-verification.resend');

});
*/
/*
public function auth()
{
    // Authentication Routes...
    $this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
    $this->post('login', 'Auth\LoginController@login');
    $this->post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    $this->post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    $this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('/resetpwd', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

app/Models/User/Agent.php
<?php
namespace App\Models\User;

use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{
    //
    protected $fillable = [
        'license','company',
    ];

}

app/Models/User/Authorizable.php
<?php

namespace App\Models\User;
/*
 * A trait to handle authorization based on users permissions for given controller
 */

trait Authorizable
{
    /**
     * Abilities
     *
     * @var array
     */
    private $abilities = [
        'index' => 'view',
        'edit' => 'edit',
        'show' => 'view',
        'update' => 'edit',
        'create' => 'add',
        'store' => 'add',
        'destroy' => 'delete'
    ];

    /**
     * Override of callAction to perform the authorization before it calls the action
     *
     * @param $method
     * @param $parameters
     * @return mixed
     */
    public function callAction($method, $parameters)
    {

        if( $ability = $this->getAbility($method) ) {

            $this->authorize($ability);
        }


        return parent::callAction($method, $parameters);
    }

    /**
     * Get ability
     *
     * @param $method
     * @return null|string
     */
    public function getAbility($method)
    {

        $routeName = explode('.', \Request::route()->getName());
        $action = array_get($this->getAbilities(), $method);

        return $action ? $action . '_' . $routeName[0] : null;
    }

    /**
     * @return array
     */
    private function getAbilities()
    {

        return $this->abilities;
    }

    /**
     * @param array $abilities
     */
    public function setAbilities($abilities)
    {
        $this->abilities = $abilities;
    }
}

app/Models/User/Permission.php
<?php

namespace App\Models\User;

class Permission extends \Spatie\Permission\Models\Permission
{

    public static function defaultPermissions()
    {
        return [
            'view_users',
            'add_users',
            'edit_users',
            'delete_users',

            'view_roles',
            'add_roles',
            'edit_roles',
            'delete_roles',

            'view_agents',
            'view_flight_contract',
            'view_calculate_commission',
            'view_issue_ticket',

        ];
    }
}

app/Models/User/Role.php
<?php

namespace App\Models\User;


class Role extends \Spatie\Permission\Models\Role
{

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User\User;
use App\Models\User\Role;
use App\Models\User\Permission;
use App\Models\User\Authorizable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    use Authorizable;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $result = User::latest()->paginate();
        if ($request->has('searchmail')){
            $email=$request->input("searchmail");
            $request->flashOnly(['searchmail']);
            $result=User::where("email",$email)->paginate();
        }

        return view('user.index', compact('result'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('name', 'id');

        return view('user.new', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'firstname' => 'bail|required|min:2',
            'lastname' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6'
        ]);

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ( $user = User::create($request->except('roles', 'permissions')) ) {
            $this->syncPermissions($request, $user);
            flash('User has been created.');

        } else {
            flash()->error('Unable to create user.');
        }

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::pluck('name', 'id');
        $permissions = Permission::all('name', 'id');

        return view('user.edit', compact('user', 'roles', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'firstname' => 'bail|required|min:2',
            'lastname' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // Update user
        $user->fill($request->except('roles', 'permissions', 'password'));

        // check for password change
        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        // Handle the user roles
        $this->syncPermissions($request, $user);

        $user->save();

        flash()->success('User has been updated.');

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @internal param Request $request
     */
    public function destroy($id)
    {
        if ( Auth::user()->id == $id ) {
            flash()->warning('Deletion of currently logged in user is not allowed :(')->important();
            return redirect()->back();
        }

        if( User::findOrFail($id)->delete() ) {
            flash()->success('User has been deleted');
        } else {
            flash()->success('User not deleted');
        }

        return redirect()->back();
    }

    /**
     * Sync roles and permissions
     *
     * @param Request $request
     * @param $user
     * @return string
     */
    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if( ! $user->hasAllRoles( $roles ) ) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);

        return $user;
    }
}

resources/views/user/_form.blade.php
<!-- Name Form Input -->
<div class="form-group @if ($errors->has('firstname')) has-error @endif">
    {!! Form::label('firstname', 'First name') !!}
    {!! Form::text('firstname', null, ['class' => 'form-control', 'placeholder' => 'First nmae']) !!}
    @if ($errors->has('firstname')) <p class="help-block">{{ $errors->first('firstname') }}</p> @endif
</div>

<div class="form-group @if ($errors->has('lastname')) has-error @endif">
    {!! Form::label('lastname', 'Last name') !!}
    {!! Form::text('lastname', null, ['class' => 'form-control', 'placeholder' => 'Last nmae']) !!}
    @if ($errors->has('lastname')) <p class="help-block">{{ $errors->first('lastname') }}</p> @endif
</div>

<!-- email Form Input -->
<div class="form-group @if ($errors->has('email')) has-error @endif">
    {!! Form::label('email', 'Email') !!}
    {!! Form::text('email', null, ['class' => 'form-control', 'placeholder' => 'Email']) !!}
    @if ($errors->has('email')) <p class="help-block">{{ $errors->first('email') }}</p> @endif
</div>

<!-- password Form Input -->
<div class="form-group @if ($errors->has('password')) has-error @endif">
    {!! Form::label('password', 'Password') !!}
    {!! Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password']) !!}
    @if ($errors->has('password')) <p class="help-block">{{ $errors->first('password') }}</p> @endif
</div>

<!-- Roles Form Input -->
<div class="form-group @if ($errors->has('roles')) has-error @endif">
    {!! Form::label('roles[]', 'Roles') !!}
    {!! Form::select('roles[]', $roles, isset($user) ? $user->roles->pluck('id')->toArray() : null,  ['class' => 'form-control', 'multiple']) !!}
    @if ($errors->has('roles')) <p class="help-block">{{ $errors->first('roles') }}</p> @endif
</div>

<!-- Permissions -->
@if(isset($user))
    @include('shared._permissions', ['closed' => 'true', 'model' => $user ])
@endif

resources/views/user/edit.blade.php
@extends('layouts.mainframe')

@section('extracss')
    <!-- Date Picker css -->
    <link rel="stylesheet" href="/bower_components/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css"/>

    <!-- Bootstrap Date-Picker css -->
    <link rel="stylesheet" href="/assets/plugins/bootstrap-datepicker/css/bootstrap-datetimepicker.css"/>
    <link rel="stylesheet" type="text/css" href="/bower_components/bootstrap-daterangepicker/daterangepicker.css"/>

@endsection

@section('content')
    <div class="content-wrapper">
        <!-- Container-fluid starts -->
        <!-- Main content starts -->
        <div class="container-fluid">

            <div class="row" style="margin-top:150px;margin-left: 15px;margin-right: 15px;">
                <div class="col-md-5">
                    <h3>Edit {{ $user->first_name }}</h3>
                </div>
                <div class="col-md-7 page-action text-right">
                    <a href="{{ route('users.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Back</a>
                </div>
            </div>

            <div class="wrapper wrapper-content animated fadeInRight" style="margin-left: 15px;margin-right: 15px;">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ibox float-e-margins">
                            <div class="ibox-content">
                                {!! Form::model($user, ['method' => 'PUT', 'route' => ['users.update',  $user->id ] ]) !!}
                                    @include('user._form')
                                    <!-- Submit Form Button -->
                                    {!! Form::submit('Save Changes', ['class' => 'btn btn-primary']) !!}
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('extrascript')

    <!-- Date picker.js -->
    <script src="/assets/plugins/datepicker/js/moment-with-locales.min.js"></script>
    <script src="/bower_components/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>

    <!-- Bootstrap Datepicker js -->
    <script type="text/javascript" src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="/assets/plugins/bootstrap-datepicker/js/bootstrap-datetimepicker.min.js"></script>

    <!-- bootstrap range picker -->
    <script type="text/javascript" src="/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>

@endsection

resources/views/user/index.blade.php
@extends('layouts.mainframe')

@section('extracss')
    <!-- Date Picker css -->
    <link rel="stylesheet" href="/bower_components/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css"/>

    <!-- Bootstrap Date-Picker css -->
    <link rel="stylesheet" href="/assets/plugins/bootstrap-datepicker/css/bootstrap-datetimepicker.css"/>
    <link rel="stylesheet" type="text/css" href="/bower_components/bootstrap-daterangepicker/daterangepicker.css"/>
    <style>
        #pagediv ul li {
            float:left;
            margin-left:5px;

        }
    </style>
@endsection

@section('content')
    <div class="content-wrapper">
        <!-- Container-fluid starts -->
        <!-- Main content starts -->
        <div class="container-fluid">
            <div class="row" style="margin-top:150px;margin-left: 15px;margin-right: 15px;">
                <div class="col-md-3">
                    <h3 class="modal-title">{{ $result->total() }} {{ str_plural('User', $result->count()) }} </h3>
                </div>
                <div class="col-md-6">
                    <form action="/users">
                        <input type="text" name="searchmail" value="{{old("searchmail")}}" maxlength="120" style="vertical-align: middle;height:35px;width:300px;"><button class="btn btn-primary btn-sm" style="margin-left:10px;">Search</button>
                    </form>

                </div>
                <div class="col-md-3 page-action text-right">
                    @can('add_users')
                        <a href="{{ route('users.create') }}" class="btn btn-primary btn-sm"> <i class="glyphicon glyphicon-plus-sign"></i> Create</a>
                    @endcan
                </div>
            </div>

            <div class="result-set" style="margin-left: 15px;margin-right: 15px;">
                <table class="table table-bordered table-striped table-hover"  id="data-table" style="background-color: navajowhite;">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Created At</th>
                        @can('edit_users', 'delete_users')
                        <th class="text-center">Actions</th>
                        @endcan
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($result as $item)
                        <tr>
                            <td>{{ $item->id }}</td>
                            <td>{{ $item->firstname . " " . $item->lastname }}</td>
                            <td>{{ $item->email }}</td>
                            <td>{{ $item->roles->implode('name', ', ') }}</td>
                            <td>{{ $item->created_at->toFormattedDateString() }}</td>

                            @can('edit_users')
                            <td class="text-center">
                                @include('shared._actions', [
                                    'entity' => 'users',
                                    'id' => $item->id
                                ])
                            </td>
                            @endcan
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                <div id="pagediv" class="text-center">
                    {{ $result->links() }}
                </div>














            </div>
        </div>
    </div>

@endsection


@section('extrascript')

    <!-- Date picker.js -->
    <script src="/assets/plugins/datepicker/js/moment-with-locales.min.js"></script>
    <script src="/bower_components/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>

    <!-- Bootstrap Datepicker js -->
    <script type="text/javascript" src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="/assets/plugins/bootstrap-datepicker/js/bootstrap-datetimepicker.min.js"></script>

    <!-- bootstrap range picker -->
    <script type="text/javascript" src="/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>

@endsection

resources/views/user/new.blade.php
@extends('layouts.mainframe')

@section('extracss')
    <!-- Date Picker css -->
    <link rel="stylesheet" href="/bower_components/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css"/>

    <!-- Bootstrap Date-Picker css -->
    <link rel="stylesheet" href="/assets/plugins/bootstrap-datepicker/css/bootstrap-datetimepicker.css"/>
    <link rel="stylesheet" type="text/css" href="/bower_components/bootstrap-daterangepicker/daterangepicker.css"/>

@endsection


@section('content')
    <div class="content-wrapper">
        <!-- Container-fluid starts -->
        <!-- Main content starts -->
        <div class="container-fluid">

            <div class="row" style="margin-top:150px;margin-left: 15px;margin-right: 15px;">
                <div class="col-md-5">
                    <h3>Create</h3>
                </div>
                <div class="col-md-7 page-action text-right">
                    <a href="{{ route('users.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Back</a>
                </div>
            </div>

            <div class="row" style="margin-left: 15px;margin-right: 15px;">
                <div class="col-lg-12">
                    {!! Form::open(['route' => ['users.store'] ]) !!}
                        @include('user._form')
                        <!-- Submit Form Button -->
                        {!! Form::submit('Create', ['class' => 'btn btn-primary']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection


@section('extrascript')

    <!-- Date picker.js -->
        <script src="/assets/plugins/datepicker/js/moment-with-locales.min.js"></script>
        <script src="/bower_components/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>

        <!-- Bootstrap Datepicker js -->
        <script type="text/javascript" src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="/assets/plugins/bootstrap-datepicker/js/bootstrap-datetimepicker.min.js"></script>

        <!-- bootstrap range picker -->
        <script type="text/javascript" src="/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>

@endsection